name: Build

env:
  CONFIGURATION: Release

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  dotnet-build:
    uses: github-actions-training/.github/.github/workflows/dotnet-build-notests.yml@main
    with:
      artifact_name: artifacts

