name: Build

env:
  CONFIGURATION: Release

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  dotnet-build:
    uses: github-actions-training/.github/.github/workflows/dotnet-build-notests.yml@main
    with:
      artifact_name: artifacts

  build-infrastructure-and-deploy:
    runs-on: ubuntu-latest
    needs: dotnet-build
    env:
      RESOURCE_GROUP_NAME: jordantools-web
      WEBAPP_NAME: jordantools
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: artifacts

      - uses: actions/download-artifact@v3
        with:
          name: infrastructure
          path: infrastructure

      # See https://github.com/marketplace/actions/azure-login#configure-a-service-principal-with-a-secret
      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create --name ${{ env.RESOURCE_GROUP_NAME }} --location australiasoutheast
            az deployment group create --resource-group ${{ env.RESOURCE_GROUP_NAME }} --template-file infrastructure/main.bicep --parameters webAppName=${{ env.WEBAPP_NAME }}

      # Deploy to Azure Web apps
      - name: 'Deploy Code'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.WEBAPP_NAME }}
          package: 'artifacts'